name       : libnice
version    : 0.1.18
release    : 3
source     :
    - https://gitlab.freedesktop.org/libnice/libnice/-/archive/0.1.18/libnice-0.1.18.tar.gz : 8bacba53e59ec6d72e9a398835c4df6446d5e0d71b2dabb7a19f6d6c5a72dcbe
license    :
    - MPL-1.1
    - LGPL-2.1-or-later
component  : programming.library
summary    : The GLib ICE implementation
description: |
    Libnice is an implementation of the IETF's Interactive Connectivity Establishment (ICE) standard (RFC 5245) and the Session Traversal Utilities for NAT (STUN) standard (RFC 5389).
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
