name       : libnice
version    : 0.1.13
release    : 1
source     :
    - http://nice.freedesktop.org/releases/libnice-0.1.13.tar.gz : 61112d9f3be933a827c8365f20551563953af6718057928f51f487bfe88419e1
license    :
    - MPL-1.1
    - LGPL-2.1
summary    : The GLib ICE implementation
description: |
    Libnice is an implementation of the IETF's Interactive Connectivity Establishment (ICE) standard (RFC 5245) and the Session Traversal Utilities for NAT (STUN) standard (RFC 5389).
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
